wallpaper {
    monitor = eDP-1
    path = ~/Pictures/Wallpapers/PalleteWallpapers/PaletteSukuna.png
    fit_mode = cover
		timeout = 600
}

wallpaper {
    monitor = 
    path = ~/Pictures/Wallpapers/PalleteWallpapers/PaletteGojo.png
    fit_mode = contain
}

# Keeps the preloaded image in memory for instant reloads/switches
splash = false
